test:
  script:
  # Install pyenv
  - apt-get update
  - apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
  - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pip install tox tox-pyenv
  - pyenv install 2.6.7
  - pyenv install 2.7.9
  - pyenv install 3.4.3
  - pyenv install pypy3.5-5.10.1
  - pyenv install 3.5.0
  - pyenv install 3.6.5
  - tox
